### ISSUE TITLE
セクション抽出: 数式イタリックが含まれる場合にテキストが <html> から始まっている

### ISSUE THREAD

**Issue by masao** [edudata-plus/tools#11]
以下のように、指導要領テキスト中にイタリックなどが含まれると `<html>` タグなどが自動的に抽出される現象あり。
要対応。

code | section | text
-|-|-
8350232100000000||<html>(1) 数の平方根，多項式と二次方程式，図形の相似，円周角と中心角の関係，三平方の定理，関数<i>y</i>＝<i>ax</i>^2，標本調査などについての基礎的な概念や原理・法則などを理解するとともに，事象を数学化したり，数学的に解釈したり，数学的に表現・処理したりする技能を身に付けるようにする。</html>

**Comment by ta-niiyan** [comment]
イタリックが含まれることがあるのですね。太字、下線などの文字修飾もあるかもしれませんね。
